spring:
  profiles:
    active: oracle
  jackson:
    serialization:
      write-dates-as-timestamps: false
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSS

---

spring:
  config:
    activate:
      on-profile: oracle
  datasource:
    url: jdbc:oracle:thin:@//192.168.1.109:1521/xepdb1
    username: nick
    password: N1C0LASm
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: none
  show-sql: true
  jackson:
    serialization:
      write-dates-as-timestamps: false
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSS

---

spring:
  config:
    activate:
      on-profile: mongo
  data:
    mongodb:
      uri: mongodb://localhost:27017/facturacion_mongo
  jackson:
    serialization:
      write-dates-as-timestamps: false
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSS
